# Generated by Django 5.2.16 on 2026-07-25 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aeronave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('capacidad', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva')], default='ACTIVA', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'aeronaves',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva')], default='ACTIVA', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rutas',
                'ordering': ['origen', 'destino'],
            },
        ),
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('PROGRAMADO', 'Programado'), ('ACTIVO', 'Activo'), ('CERRADO', 'Cerrado'), ('CANCELADO', 'Cancelado')], default='PROGRAMADO', max_length=20)),
                ('cupos_disponibles', models.PositiveIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('aeronave', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vuelos', to='vuelos.aeronave')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vuelos', to='vuelos.ruta')),
            ],
            options={
                'db_table': 'vuelos',
                'ordering': ['fecha', 'hora'],
            },
        ),
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RESERVADO', 'Reservado'), ('BLOQUEADO', 'Bloqueado')], default='DISPONIBLE', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asientos', to='vuelos.vuelo')),
            ],
            options={
                'db_table': 'asientos',
                'ordering': ['vuelo', 'numero'],
                'constraints': [models.UniqueConstraint(fields=('vuelo', 'numero'), name='unique_asiento_por_vuelo')],
            },
        ),
    ]
