# Generated by Django 5.2.16 on 2026-07-27 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeronave',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'Activa'), ('MANTENIMIENTO', 'Mantenimiento'), ('INACTIVA', 'Inactiva')], default='ACTIVA', max_length=20),
        ),
    ]
