# Generated by Django 5.2.16 on 2026-07-20 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100)),
                ('entidad', models.CharField(blank=True, max_length=100)),
                ('entidad_id', models.CharField(blank=True, max_length=100)),
                ('resultado', models.CharField(choices=[('EXITO', 'Éxito'), ('ERROR', 'Error'), ('DENEGADO', 'Denegado')], default='EXITO', max_length=20)),
                ('detalle', models.TextField(blank=True)),
                ('metodo_http', models.CharField(blank=True, max_length=10)),
                ('endpoint', models.CharField(blank=True, max_length=255)),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_bitacora', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'evento de bitácora',
                'verbose_name_plural': 'bitácora',
                'db_table': 'bitacora',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['usuario', 'creado_en'], name='bitacora_usuario_fecha_idx'), models.Index(fields=['accion'], name='bitacora_accion_idx'), models.Index(fields=['resultado'], name='bitacora_resultado_idx')],
            },
        ),
    ]
