# Generated by Django 5.2.16 on 2026-07-20 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SEGURIDAD', 'Seguridad'), ('RESERVA', 'Reserva'), ('PAGO', 'Pago'), ('VUELO', 'Vuelo'), ('SISTEMA', 'Sistema')], default='SISTEMA', max_length=20)),
                ('titulo', models.CharField(max_length=150)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('leida_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notificación',
                'verbose_name_plural': 'notificaciones',
                'db_table': 'notificaciones',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['usuario', 'leida'], name='notif_usuario_leida_idx'), models.Index(fields=['tipo'], name='notif_tipo_idx')],
            },
        ),
    ]
