# Generated by Django 5.2.16 on 2026-07-30 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vuelos', '0002_alter_aeronave_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], default='CONFIRMADA', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='vuelos.asiento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to=settings.AUTH_USER_MODEL)),
                ('vuelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='vuelos.vuelo')),
            ],
            options={
                'db_table': 'reservas',
                'ordering': ['-creado_en'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('estado', 'CONFIRMADA')), fields=('vuelo', 'asiento'), name='unique_asiento_reserva_confirmada')],
            },
        ),
    ]
