# Generated by Django 5.2.16 on 2026-07-30 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reserva',
            name='unique_asiento_reserva_confirmada',
        ),
    ]
