# Generated by Django 5.2.16 on 2026-08-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_pago_codigo_verificacion_pago_cuenta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='codigo_verificacion',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
