# Generated by Django 5.2.16 on 2026-08-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_alter_pago_codigo_verificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='codigo_verificacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
