# Generated by Django 5.2.16 on 2026-07-20 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_hash', models.CharField(max_length=128)),
                ('expira_en', models.DateTimeField()),
                ('usado', models.BooleanField(default=False)),
                ('intentos', models.PositiveSmallIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_otp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'código OTP',
                'verbose_name_plural': 'códigos OTP',
                'db_table': 'codigos_otp',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['usuario', 'usado'], name='otp_usuario_usado_idx'), models.Index(fields=['expira_en'], name='otp_expiracion_idx')],
            },
        ),
    ]
